"""Loader for the deterministic, versioned trusted-content artifacts.

These files are generated by `yarn content:export` from the authored content
bundle. The server trusts ONLY these files for reward determination — never
reward data supplied by the browser at runtime.
"""
import json
import os
from typing import Any, Dict, List, Optional

_HERE = os.path.dirname(os.path.abspath(__file__))
_TRUSTED_DIR = os.path.join(_HERE, "..", "trusted_content")
_REGISTRY = os.path.join(_TRUSTED_DIR, "registry.json")
_FIXTURES = os.path.join(_TRUSTED_DIR, "parity_fixtures.json")


def load_registry(path: Optional[str] = None) -> Dict[str, Any]:
    with open(path or _REGISTRY, "r", encoding="utf-8") as f:
        return json.load(f)


def load_fixtures(path: Optional[str] = None) -> List[Dict[str, Any]]:
    with open(path or _FIXTURES, "r", encoding="utf-8") as f:
        return json.load(f)


def book_entry(registry: Dict[str, Any], book_id: str, version: int) -> Dict[str, Any]:
    """Return the trusted content for a specific (book, version), or raise.

    Content versions are pinned: an event authored against a version the server
    does not hold is rejected rather than silently applied against a different
    version's rules.
    """
    book = registry.get("books", {}).get(book_id)
    if book is None or book.get("version") != version:
        raise UnknownContentVersion(f"no trusted content for {book_id} v{version}")
    return book


class ReducerError(Exception):
    """Base class for deterministic reducer rejections."""


class InvalidChoice(ReducerError):
    """Choice/scene not present in trusted content, or scene not reachable."""


class UnknownContentVersion(ReducerError):
    """Event references a (book, version) the server does not hold."""
