import React from 'react';
import { Sparkles } from 'lucide-react';
import { AdminAiDraftRequest, AdminAiStatus, AdminDraft, generateAdminDraft, getAdminAiStatus } from '../../sync/cloudClient';

export const AiDraftGenerator: React.FC<{ onGenerated: (draft: AdminDraft) => void }> = ({ onGenerated }) => {
  const [status, setStatus] = React.useState<AdminAiStatus | null | undefined>(undefined);
  const [form, setForm] = React.useState<AdminAiDraftRequest>({ bookId: 'book2', desiredTitle: '', premise: '' });
  const [working, setWorking] = React.useState(false);
  const [notice, setNotice] = React.useState<string | null>(null);
  React.useEffect(() => { void getAdminAiStatus().then(setStatus).catch(() => setStatus(null)); }, []);
  const generate = async () => { if (form.premise.trim().length < 20) { setNotice('Write a premise of at least 20 characters first.'); return; } setWorking(true); setNotice(null); try { const draft = await generateAdminDraft(form); onGenerated(draft); setNotice('Generated a private draft. Review and edit it before marking it ready for review.'); } catch (error) { setNotice(error instanceof Error && error.message === 'openrouter_not_configured' ? 'OpenRouter is not configured in this Vercel environment yet.' : 'The AI could not produce a valid draft. Try a more focused premise.'); } finally { setWorking(false); } };
  if (status === undefined) return null;
  return <section className="mt-6 rounded-xl border border-[#c5a059]/30 bg-[#150f1f] p-5"><div className="flex items-start gap-3"><Sparkles className="mt-1 h-5 w-5 text-[#e5c158]" /><div><h2 className="font-display text-xl text-[#f5f0e6]">AI draft assistant</h2><p className="mt-1 text-sm text-stone-400">Creates a private, editable draft only. You remain responsible for review and publication.</p></div></div>{!status?.configured ? <p className="mt-4 rounded border border-dashed border-white/15 p-3 text-sm text-stone-400">Add <code>OPENROUTER_API_KEY</code> to this Vercel environment to enable generation.</p> : <><p className="mt-3 text-xs text-stone-500">Using {status.model}</p><label className="mt-4 block text-sm text-stone-300">Book ID<input value={form.bookId} onChange={(e) => setForm({ ...form, bookId: e.target.value })} className="mt-1 w-full rounded border border-white/15 bg-black/20 p-2 text-[#f5f0e6]" /></label><label className="mt-3 block text-sm text-stone-300">Desired title (optional)<input value={form.desiredTitle} onChange={(e) => setForm({ ...form, desiredTitle: e.target.value })} className="mt-1 w-full rounded border border-white/15 bg-black/20 p-2 text-[#f5f0e6]" /></label><label className="mt-3 block text-sm text-stone-300">Story premise<textarea rows={4} value={form.premise} onChange={(e) => setForm({ ...form, premise: e.target.value })} placeholder="A mysterious invitation brings the player to Blackthorn Academy..." className="mt-1 w-full rounded border border-white/15 bg-black/20 p-2 text-[#f5f0e6]" /></label><button disabled={working} onClick={() => void generate()} className="mt-4 inline-flex items-center gap-2 rounded bg-[#7d0828] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Sparkles className="h-4 w-4" />{working ? 'Generating…' : 'Generate private draft'}</button></>}{notice && <p className="mt-3 text-sm text-[#e5c158]">{notice}</p>}</section>;
};
