import React from 'react';
import { Pencil, Plus, Trash2, Users } from 'lucide-react';
import { AdminCharacter, createAdminCharacter, deleteAdminCharacter, getAdminCharacters, updateAdminCharacter } from '../../sync/cloudClient';

const blank: AdminCharacter = { characterId: '', displayName: '', defaultMood: 'neutral' };

export const CharacterCatalogue: React.FC = () => {
  const [characters, setCharacters] = React.useState<AdminCharacter[] | null>(null);
  const [form, setForm] = React.useState<AdminCharacter>(blank);
  const [editing, setEditing] = React.useState<string | null>(null);
  const [notice, setNotice] = React.useState<string | null>(null);
  React.useEffect(() => { void getAdminCharacters().then(setCharacters).catch(() => setCharacters([])); }, []);
  const save = async () => {
    if (!form.characterId.trim() || !form.displayName.trim()) { setNotice('Give the character an ID and display name.'); return; }
    if (!editing && (characters ?? []).some((item) => item.characterId.toLowerCase() === form.characterId.trim().toLowerCase())) { setNotice('That stable character ID already exists. Choose the existing character to edit it.'); return; }
    try { const saved = editing ? await updateAdminCharacter(form) : await createAdminCharacter(form); setCharacters((items) => [...(items ?? []).filter((item) => item.characterId !== saved.characterId), saved].toSorted((a, b) => a.displayName.localeCompare(b.displayName))); setForm(blank); setEditing(null); setNotice(editing ? 'Character updated.' : 'Character added to the private authoring catalogue.'); } catch { setNotice(editing ? 'Could not update this character.' : 'That stable character ID already exists.'); }
  };
  const edit = (character: AdminCharacter) => { setForm(character); setEditing(character.characterId); setNotice(null); };
  const remove = async (character: AdminCharacter) => { if (!window.confirm(`Remove ${character.displayName} from the private character catalogue? Existing dialogue keeps its saved name.`)) return; try { await deleteAdminCharacter(character.characterId); setCharacters((items) => (items ?? []).filter((item) => item.characterId !== character.characterId)); if (editing === character.characterId) { setForm(blank); setEditing(null); } setNotice('Character removed from the catalogue.'); } catch { setNotice('Could not remove the character.'); } };
  return <section className="mt-6 rounded-xl border border-white/10 bg-[#150f1f] p-5"><h2 className="flex items-center gap-2 font-display text-xl text-[#f5f0e6]"><Users className="h-5 w-5 text-[#e5c158]" />Character catalogue</h2><p className="mt-1 text-sm text-stone-400">Stable IDs are reusable story data. Dialogue selects these characters and fills their display name and mood.</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={form.characterId} readOnly={Boolean(editing)} onChange={(event) => setForm({ ...form, characterId: event.target.value })} placeholder="Stable ID, e.g. professor-vale" className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6] read-only:text-stone-400" /><input value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} placeholder="Display name" className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /><input value={form.defaultMood} onChange={(event) => setForm({ ...form, defaultMood: event.target.value })} placeholder="Default mood" className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /></div><div className="mt-3 flex gap-2"><button onClick={() => void save()} className="inline-flex items-center gap-1 rounded border border-[#c5a059]/70 px-3 py-2 text-sm text-[#e5c158]"><Plus className="h-4 w-4" />{editing ? 'Save character' : 'Add character'}</button>{editing && <button onClick={() => { setForm(blank); setEditing(null); }} className="rounded border border-white/15 px-3 py-2 text-sm text-stone-300">Cancel</button>}</div>{notice && <p className="mt-2 text-sm text-[#e5c158]">{notice}</p>}{characters && characters.length > 0 && <div className="mt-4 grid gap-2">{characters.map((character) => <div key={character.characterId} className="flex items-center justify-between gap-3 rounded border border-white/10 p-2 text-sm text-stone-300"><span><strong className="text-[#f5f0e6]">{character.displayName}</strong> · {character.characterId} · {character.defaultMood}</span><span className="flex gap-2"><button onClick={() => edit(character)} className="text-[#e5c158]" title="Edit character"><Pencil className="h-4 w-4" /></button><button onClick={() => void remove(character)} className="text-rose-300" title="Remove character"><Trash2 className="h-4 w-4" /></button></span></div>)}</div>}</section>;
};
