import React from 'react';
import { MessageCircle, Plus, Save, Trash2 } from 'lucide-react';
import { AdminCharacter, AdminChoice, AdminDialogue, AdminDraft, AdminScene, getAdminCharacters, updateAdminDraftScenes } from '../../sync/cloudClient';

const blankChoice = (): AdminChoice => ({ choiceId: '', text: '', nextSceneId: '', effectsNotes: '' });
const blankDialogue = (): AdminDialogue => ({ speakerId: '', displayName: '', text: '', mood: 'neutral' });
const blankScene = (): AdminScene => ({ sceneId: '', chapterNumber: 1, title: '', body: '', dialogue: [], choices: [blankChoice()] });

export const ManualSceneEditor: React.FC<{ draft: AdminDraft; onSaved: (draft: AdminDraft) => void }> = ({ draft, onSaved }) => {
  const [scenes, setScenes] = React.useState<AdminScene[]>(draft.scenes ?? []);
  const [saving, setSaving] = React.useState(false);
  const [notice, setNotice] = React.useState<string | null>(null);
  const [characters, setCharacters] = React.useState<AdminCharacter[]>([]);
  React.useEffect(() => { setScenes(draft.scenes ?? []); setNotice(null); }, [draft.draftId, draft.revision]);
  React.useEffect(() => { void getAdminCharacters().then((items) => setCharacters(items ?? [])).catch(() => setCharacters([])); }, []);
  const changeScene = (index: number, change: Partial<AdminScene>) => setScenes((items) => items.map((scene, i) => i === index ? { ...scene, ...change } : scene));
  const changeChoice = (sceneIndex: number, choiceIndex: number, change: Partial<AdminChoice>) => setScenes((items) => items.map((scene, i) => i !== sceneIndex ? scene : { ...scene, choices: scene.choices.map((choice, j) => j === choiceIndex ? { ...choice, ...change } : choice) }));
  const changeDialogue = (sceneIndex: number, dialogueIndex: number, change: Partial<AdminDialogue>) => setScenes((items) => items.map((scene, i) => i !== sceneIndex ? scene : { ...scene, dialogue: (scene.dialogue ?? []).map((line, j) => j === dialogueIndex ? { ...line, ...change } : line) }));
  const chooseSpeaker = (sceneIndex: number, dialogueIndex: number, characterId: string) => { const character = characters.find((item) => item.characterId === characterId); if (character) changeDialogue(sceneIndex, dialogueIndex, { speakerId: character.characterId, displayName: character.displayName, mood: character.defaultMood }); };
  const save = async () => {
    if (scenes.some((scene) => !scene.sceneId.trim() || !scene.title.trim() || !scene.body.trim() || scene.choices.some((choice) => !choice.choiceId.trim() || !choice.text.trim()) || (scene.dialogue ?? []).some((line) => !line.speakerId.trim() || !line.displayName.trim() || !line.text.trim()))) { setNotice('Each scene needs an ID, title and story text. Choices and dialogue lines also need their required fields.'); return; }
    setSaving(true); setNotice(null);
    try { const saved = await updateAdminDraftScenes(draft.draftId, scenes, draft.revision); onSaved(saved); setNotice('Scenes saved to this private draft.'); }
    catch (error) { setNotice(error instanceof Error && error.message === 'draft_conflict' ? 'This draft changed elsewhere. Select it again, then save.' : 'Could not save scenes.'); }
    finally { setSaving(false); }
  };
  return <section className="mt-6 rounded-xl border border-white/10 bg-[#150f1f] p-5">
    <div><h2 className="font-display text-xl text-[#f5f0e6]">Manual scenes & choices</h2><p className="mt-1 text-sm text-stone-400">Use controlled tokens such as <code>{'{{player.name}}'}</code> and <code>{'{{player.species}}'}</code>. This remains private until a later publishing phase.</p></div>
    <div className="mt-5 grid gap-5">{scenes.map((scene, sceneIndex) => <article key={sceneIndex} className="rounded-lg border border-white/10 bg-black/15 p-4">
      <div className="flex items-center justify-between gap-3"><strong className="text-[#f5f0e6]">Scene {sceneIndex + 1}</strong><button onClick={() => setScenes((items) => items.filter((_, i) => i !== sceneIndex))} className="text-rose-300" title="Remove scene"><Trash2 className="h-4 w-4" /></button></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-[1fr_110px]"><label className="text-sm text-stone-300">Scene ID<input value={scene.sceneId} onChange={(e) => changeScene(sceneIndex, { sceneId: e.target.value })} placeholder="chapter-1-arrival" className="mt-1 w-full rounded border border-white/15 bg-black/20 p-2 text-[#f5f0e6]" /></label><label className="text-sm text-stone-300">Chapter<input type="number" min="1" value={scene.chapterNumber} onChange={(e) => changeScene(sceneIndex, { chapterNumber: Number(e.target.value) || 1 })} className="mt-1 w-full rounded border border-white/15 bg-black/20 p-2 text-[#f5f0e6]" /></label></div>
      <label className="mt-3 block text-sm text-stone-300">Scene title<input value={scene.title} onChange={(e) => changeScene(sceneIndex, { title: e.target.value })} className="mt-1 w-full rounded border border-white/15 bg-black/20 p-2 text-[#f5f0e6]" /></label><label className="mt-3 block text-sm text-stone-300">Story text<textarea rows={6} value={scene.body} onChange={(e) => changeScene(sceneIndex, { body: e.target.value })} className="mt-1 w-full rounded border border-white/15 bg-black/20 p-2 text-[#f5f0e6]" /></label>
      <div className="mt-4"><p className="flex items-center gap-2 text-sm font-semibold text-[#c5a059]"><MessageCircle className="h-4 w-4" />Dialogue beats</p>{(scene.dialogue ?? []).map((line, lineIndex) => <div key={lineIndex} className="mt-2 rounded border border-white/10 p-3"><div className="flex justify-end"><button onClick={() => changeScene(sceneIndex, { dialogue: (scene.dialogue ?? []).filter((_, i) => i !== lineIndex) })} className="text-rose-300" title="Remove dialogue"><Trash2 className="h-4 w-4" /></button></div><div className="grid gap-2 sm:grid-cols-3"><select value={line.speakerId} onChange={(e) => chooseSpeaker(sceneIndex, lineIndex, e.target.value)} className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]"><option value="">Choose catalogue character</option>{line.speakerId && !characters.some((character) => character.characterId === line.speakerId) && <option value={line.speakerId}>{line.speakerId} (external)</option>}{characters.map((character) => <option key={character.characterId} value={character.characterId}>{character.displayName} · {character.characterId}</option>)}</select><input value={line.displayName} readOnly placeholder="Filled from catalogue" className="rounded border border-white/15 bg-black/30 p-2 text-sm text-stone-300" /><input value={line.mood} onChange={(e) => changeDialogue(sceneIndex, lineIndex, { mood: e.target.value })} placeholder="Mood" className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /></div><textarea rows={3} value={line.text} onChange={(e) => changeDialogue(sceneIndex, lineIndex, { text: e.target.value })} placeholder="Dialogue text — {{speaker.name}} can use the display name" className="mt-2 w-full rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /></div>)}<button onClick={() => changeScene(sceneIndex, { dialogue: [...(scene.dialogue ?? []), blankDialogue()] })} className="mt-3 inline-flex items-center gap-1 text-sm text-[#e5c158]"><Plus className="h-4 w-4" />Add dialogue</button></div>
      <div className="mt-4"><p className="text-sm font-semibold text-[#c5a059]">Choices</p>{scene.choices.map((choice, choiceIndex) => <div key={choiceIndex} className="mt-2 rounded border border-white/10 p-3"><div className="flex justify-end"><button onClick={() => changeScene(sceneIndex, { choices: scene.choices.filter((_, i) => i !== choiceIndex) })} className="text-rose-300" title="Remove choice"><Trash2 className="h-4 w-4" /></button></div><div className="grid gap-2 sm:grid-cols-2"><input value={choice.choiceId} onChange={(e) => changeChoice(sceneIndex, choiceIndex, { choiceId: e.target.value })} placeholder="Choice ID" className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /><input value={choice.nextSceneId ?? ''} onChange={(e) => changeChoice(sceneIndex, choiceIndex, { nextSceneId: e.target.value })} placeholder="Next scene ID (blank ends route)" className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /></div><input value={choice.text} onChange={(e) => changeChoice(sceneIndex, choiceIndex, { text: e.target.value })} placeholder="What the player sees" className="mt-2 w-full rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /><input value={choice.effectsNotes} onChange={(e) => changeChoice(sceneIndex, choiceIndex, { effectsNotes: e.target.value })} placeholder="Private consequence notes (optional)" className="mt-2 w-full rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /></div>)}<button onClick={() => changeScene(sceneIndex, { choices: [...scene.choices, blankChoice()] })} className="mt-3 inline-flex items-center gap-1 text-sm text-[#e5c158]"><Plus className="h-4 w-4" />Add choice</button></div>
    </article>)}</div>
    {notice && <p className="mt-4 text-sm text-[#e5c158]">{notice}</p>}<div className="mt-5 flex flex-wrap gap-3"><button onClick={() => setScenes((items) => [...items, blankScene()])} className="inline-flex items-center gap-2 rounded border border-[#c5a059]/70 px-4 py-2 text-sm font-semibold text-[#e5c158]"><Plus className="h-4 w-4" />Add scene</button><button disabled={saving} onClick={() => void save()} className="inline-flex items-center gap-2 rounded bg-[#7d0828] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'Saving…' : 'Save scenes'}</button></div>
  </section>;
};
