import React from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { AdminCharacter, getAdminCharacters } from '../../sync/cloudClient';

export const PlaytestSettings: React.FC<{ values: Record<string, number>; onChange: (values: Record<string, number>) => void }> = ({ values, onChange }) => {
  const [characters, setCharacters] = React.useState<AdminCharacter[]>([]);
  React.useEffect(() => { void getAdminCharacters().then((items) => setCharacters(items ?? [])).catch(() => setCharacters([])); }, []);
  const rows = Object.entries(values) as Array<[string, number]>;
  const update = (oldKey: string, key: string, value: number) => { const next = { ...values }; delete next[oldKey]; if (key) next[key] = value; onChange(next); };
  return <section className="mt-4 rounded border border-[#c5a059]/25 bg-black/10 p-3"><h3 className="text-sm font-semibold text-[#c5a059]">Private playtest starting values</h3><p className="mt-1 text-xs text-stone-500">These are test-only values. They never read or update a player’s real humanity, blood coins, or affinity.</p>{rows.map(([key, value]) => <div key={key} className="mt-2 grid gap-2 sm:grid-cols-[1fr_130px_auto]"><select value={key} onChange={(event) => update(key, event.target.value, value)} className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]"><option value="humanity">Humanity</option><option value="bloodCoins">Blood Coins</option>{key.startsWith('affinity.') && !characters.some((character) => `affinity.${character.characterId}` === key) && <option value={key}>{key} (existing)</option>}{characters.map((character) => <option key={character.characterId} value={`affinity.${character.characterId}`}>Affinity: {character.displayName}</option>)}</select><input type="number" value={value} onChange={(event) => update(key, key, Number(event.target.value) || 0)} className="rounded border border-white/15 bg-black/20 p-2 text-sm text-[#f5f0e6]" /><button onClick={() => { const next = { ...values }; delete next[key]; onChange(next); }} className="text-rose-300" title="Remove starting value"><Trash2 className="h-4 w-4" /></button></div>)}{rows.length < 20 && <button onClick={() => { const available = characters.find((character) => !values[`affinity.${character.characterId}`]); if (available) onChange({ ...values, [`affinity.${available.characterId}`]: 0 }); }} disabled={!characters.some((character) => !values[`affinity.${character.characterId}`])} className="mt-3 inline-flex items-center gap-1 text-sm text-[#e5c158] disabled:opacity-50"><Plus className="h-4 w-4" />Add character affinity</button>}</section>;
};
