import React from 'react';
import { CheckCircle2, Eye, LoaderCircle, Send, TriangleAlert } from 'lucide-react';
import { AdminDraft, PublishReadiness, getAdminDraftPublishReadiness, prepareAdminDraftPublication } from '../../sync/cloudClient';

const statusLabel: Record<PublishReadiness['status'], string> = { needs_attention: 'Needs attention', ready_for_approval: 'Ready for approval', approved: 'Approved', ready_to_publish: 'Ready to publish' };

export const PublishWorkflow: React.FC<{ draft: AdminDraft; onPreview: () => void; onApproved: () => void }> = ({ draft, onPreview, onApproved }) => {
  const [readiness, setReadiness] = React.useState<PublishReadiness | null>(null);
  const [busy, setBusy] = React.useState(false);
  const [notice, setNotice] = React.useState<string | null>(null);
  const refresh = React.useCallback(async () => { try { setReadiness(await getAdminDraftPublishReadiness(draft.draftId)); } catch { setReadiness(null); } }, [draft.draftId, draft.revision]);
  React.useEffect(() => { void refresh(); }, [refresh]);
  const prepare = async () => { setBusy(true); setNotice(null); try { const result = await prepareAdminDraftPublication(draft.draftId); setReadiness(result.readiness); setNotice('Release preparation completed. The immutable candidate is ready for the final, separately controlled live activation.'); } catch { setNotice('Preparation was blocked. Review the readiness panel and correct the listed issue.'); } finally { setBusy(false); } };
  const checks = readiness ? [['Story graph', readiness.summary.graphPassed], ['Dynamic tokens', readiness.summary.tokensPassed], ['Mechanics', readiness.summary.mechanicsPassed]] : [];
  return <section className="rounded-xl border border-emerald-400/25 bg-emerald-950/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-200">Simple publishing workflow</p><h2 className="mt-1 font-display text-2xl text-[#f5f0e6]">{readiness ? statusLabel[readiness.status] : 'Checking book status…'}</h2><p className="mt-1 text-sm text-stone-300">Preview, approve, then prepare a checksum-bound publication candidate. Advanced release tools remain available below.</p></div>{readiness && <span className="rounded border border-emerald-300/35 px-2 py-1 text-xs text-emerald-100">Revision {readiness.revision}</span>}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{readiness && <><div className="rounded bg-black/20 p-3 text-sm text-stone-200"><strong>{readiness.summary.sceneCount}</strong><br />scenes</div><div className="rounded bg-black/20 p-3 text-sm text-stone-200"><strong>{readiness.summary.choiceCount}</strong><br />choices</div>{checks.map(([label, passed]) => <div key={String(label)} className="rounded bg-black/20 p-3 text-sm text-stone-200"><span className={passed ? 'text-emerald-300' : 'text-rose-300'}>{passed ? 'Passed' : 'Blocked'}</span><br />{label}</div>)}</>}</div>{readiness?.blockers.length ? <div className="mt-4 rounded border border-rose-400/30 bg-rose-950/20 p-3 text-sm text-rose-100"><strong className="flex items-center gap-2"><TriangleAlert className="h-4 w-4" />Publishing blocked</strong><ul className="mt-2 list-disc space-y-1 pl-5">{readiness.blockers.map((blocker) => <li key={blocker.code}>{blocker.message}</li>)}</ul></div> : null}<div className="mt-5 flex flex-wrap gap-3"><button onClick={onPreview} className="inline-flex items-center gap-2 rounded border border-sky-300/60 px-4 py-2 text-sm font-semibold text-sky-100"><Eye className="h-4 w-4" />Preview Book</button>{readiness?.recommendedAction === 'approve_for_publication' && <button onClick={onApproved} className="inline-flex items-center gap-2 rounded border border-emerald-400/60 px-4 py-2 text-sm font-semibold text-emerald-100"><CheckCircle2 className="h-4 w-4" />Approve for Publication</button>}{readiness?.recommendedAction === 'prepare_publication' && <button disabled={busy} onClick={() => void prepare()} className="inline-flex items-center gap-2 rounded bg-[#7d0828] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{busy ? 'Preparing…' : 'Publish Book'}</button>}{readiness?.recommendedAction === 'publish_confirmation' && <p className="self-center text-sm text-emerald-200">Preparation passed. Final player-facing activation is intentionally kept as a separate confirmation.</p>}<button onClick={() => void refresh()} className="text-sm text-stone-300">Refresh status</button></div>{notice && <p className="mt-3 text-sm text-[#e5c158]">{notice}</p>}</section>;
};
