import React from 'react';
import { Download, History, PackageCheck, Rocket, RotateCcw, ShieldCheck } from 'lucide-react';
import { AdminDraft, AdminReleaseVersion, createAdminReleaseVersion, getAdminReleaseVersion, getAdminReleaseVersions, selectAdminReleaseVersion, stageAdminReleaseVersion } from '../../sync/cloudClient';

export const ReleaseRegistry: React.FC<{ draft: AdminDraft; onNotice: (message: string) => void }> = ({ draft, onNotice }) => {
  const [releases, setReleases] = React.useState<AdminReleaseVersion[] | null>(null);
  const [working, setWorking] = React.useState(false);
  const refresh = async () => setReleases(await getAdminReleaseVersions());
  React.useEffect(() => { void refresh().catch(() => setReleases([])); }, []);
  const prepare = async () => { setWorking(true); try { const release = await createAdminReleaseVersion(draft.draftId); await refresh(); onNotice(`Release v${release.version} is frozen in the private registry. It is not live player content.`); } catch { onNotice('Could not create the release version. Approve a valid draft first.'); } finally { setWorking(false); } };
  const select = async (release: AdminReleaseVersion) => { setWorking(true); try { const rollback = release.status !== 'selected'; await selectAdminReleaseVersion(release.releaseId, rollback); await refresh(); onNotice(rollback ? `Rolled back the private registry to v${release.version}. No player content changed.` : `Release v${release.version} remains selected for later rollout.`); } catch { onNotice('Could not update the selected release version.'); } finally { setWorking(false); } };
  const stage = async (release: AdminReleaseVersion) => { setWorking(true); try { await stageAdminReleaseVersion(release.releaseId); await refresh(); onNotice(`Release v${release.version} is now available through the flag-gated staging preview only. It still cannot read or update player saves.`); } catch { onNotice('Could not stage this version. Add STAGED_RELEASE_PREVIEW=true to this Preview environment, then redeploy.'); } finally { setWorking(false); } };
  const download = async (release: AdminReleaseVersion) => { setWorking(true); try { const snapshot = await getAdminReleaseVersion(release.releaseId); const url = URL.createObjectURL(new Blob([JSON.stringify(snapshot, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `${release.bookId}-release-v${release.version}.json`; link.click(); URL.revokeObjectURL(url); onNotice(`Downloaded frozen release v${release.version} for review. It is not player-facing.`); } catch { onNotice('Could not download the frozen release snapshot.'); } finally { setWorking(false); } };
  const bookReleases = (releases ?? []).filter((release) => release.bookId === draft.bookId);
  return <section className="mt-6 rounded-xl border border-[#c5a059]/30 bg-[#150f1f] p-5">
    <div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-[#e5c158]" /><div><h2 className="font-display text-xl text-[#f5f0e6]">Release registry</h2><p className="mt-1 text-sm text-stone-400">Immutable approved snapshots and rollback selection. The player app cannot read this registry yet.</p></div></div>
    {draft.status === 'approved_for_release' ? <button disabled={working} onClick={() => void prepare()} className="mt-4 inline-flex items-center gap-2 rounded border border-emerald-400/60 px-3 py-2 text-sm text-emerald-200 disabled:opacity-50"><PackageCheck className="h-4 w-4" />{working ? 'Preparing…' : 'Freeze release version'}</button> : <p className="mt-4 text-sm text-stone-500">Approve this draft before freezing a release version.</p>}
    <div className="mt-5"><h3 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#c5a059]"><History className="h-4 w-4" />{draft.bookId} release history</h3>{releases === null ? <p className="mt-2 text-sm text-stone-400">Loading release history…</p> : bookReleases.length === 0 ? <p className="mt-2 text-sm text-stone-500">No release versions yet.</p> : <div className="mt-3 grid gap-2">{bookReleases.map((release) => <article key={release.releaseId} className="rounded border border-white/10 bg-black/15 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-[#f5f0e6]">Version {release.version}</strong><span className={release.status === 'staged' ? 'text-xs text-sky-300' : release.status === 'selected' ? 'text-xs text-emerald-300' : 'text-xs text-stone-400'}>{release.status === 'staged' ? 'Staging preview active' : release.status === 'selected' ? 'Selected for later rollout' : 'Prepared'}</span></div><p className="mt-1 text-xs text-stone-500">Approved revision {release.source.approvedRevision} · {release.manifest.sceneCount} scenes · checksum {release.manifest.sha256.slice(0, 12)}…</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={working} onClick={() => void download(release)} className="inline-flex items-center gap-2 rounded border border-white/15 px-2 py-1 text-xs text-stone-200 disabled:opacity-50"><Download className="h-3.5 w-3.5" />Download snapshot</button>{release.status === 'selected' && <button disabled={working} onClick={() => void stage(release)} className="inline-flex items-center gap-2 rounded border border-sky-400/60 px-2 py-1 text-xs text-sky-200 disabled:opacity-50"><Rocket className="h-3.5 w-3.5" />Stage preview</button>}{release.status === 'staged' ? <p className="text-xs text-sky-200">Staged by {release.stagedBy}; endpoint: <code>/api/staged-releases/{release.bookId}</code></p> : release.status === 'selected' ? <p className="text-xs text-stone-400">Selected by {release.selectedBy}.</p> : <button disabled={working} onClick={() => void select(release)} className="inline-flex items-center gap-2 rounded border border-[#c5a059]/60 px-2 py-1 text-xs text-[#e5c158] disabled:opacity-50"><RotateCcw className="h-3.5 w-3.5" />Select / rollback to this version</button>}</div></article>)}</div>}</div>
  </section>;
};
